data:
  build: ./data-only
  volumes:
    - ./data-only/app:/var/app
    - /var/lib/mysql

# from docker library/mysql:5.7
mysql:
  image: mysql:5.7
  volumes_from:
    - data
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: 4321qaz
    MYSQL_DATABASE: sample

# from custom image extends docker libaray/php:5.6-fpm
php:
  build: ./php-fpm
  links:
    - mysql
  ports:
    - 9000
  volumes_from:
    - data

nginx:
  build: ./nginx
  links:
    - php:php-fpm
  ports:
    - 80
  volumes_from:
    - data

nginx2:
  build: ./nginx
  links:
    - php:php-fpm
  ports:
    - 80
  volumes_from:
    - data

varnish:
  build: ./varnish
  links:
    - nginx:nginx
    - nginx2:nginx2
  ports:
   - 80:80